const router = require("express").Router();
const { loginRequired, allowedRole } = require("../../middlewares/authMiddlewares");
const { body, param } = require("express-validator");
const { formChacker } = require("../../middlewares/formMiddleware");
const c = require("./controllers_pin");
const manager = [loginRequired, allowedRole("ADMIN", "OPERATOR")];
router.get("/list", ...manager, c.listPins);
router.post("/register", ...manager, body("pin").notEmpty().isNumeric().isLength({min:6,max:6}), body("deviceId").notEmpty().isString(), body("targetUserId").notEmpty().isUUID(), formChacker, c.registerPin);
router.post("/update/:pinId", ...manager, param("pinId").notEmpty(), body("newPin").notEmpty().isNumeric().isLength({min:6,max:6}), formChacker, c.updatePin);
router.delete("/delete/:pinId", ...manager, param("pinId").notEmpty(), c.deletePin);
module.exports = router;
