-- CreateEnum
CREATE TYPE "AUTHENTICATION_METHOD" AS ENUM ('RFID', 'FINGERPRINT', 'PIN', 'FACE', 'EXIT_BUTTON', 'UNKNOWN');

-- AlterTable
ALTER TABLE "Rooms_Records" ADD COLUMN     "authenticationMethod" "AUTHENTICATION_METHOD" NOT NULL DEFAULT 'UNKNOWN';
